package whatisnewin.java.util.function;

import java.util.function.Predicate;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Predicate}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Predicate} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see Predicate
 */
public final class WhatIsNewInPredicate<T>
{
  /**
   * Example call to new method {@link Predicate#not(Predicate)}.
   * @since 11
   * @see Predicate#not(Predicate)
   */
  public static <T> Predicate<T> not(Predicate<? super T> target)
  {
    Predicate<T> result = Predicate.not(target);
    return result;
  }

}
