package whatisnewin.java.net.http;

import java.net.http.HttpRequest;
import java.util.Optional;
import java.time.Duration;
import java.net.http.HttpRequest.Builder;
import java.net.URI;
import java.net.http.HttpClient.Version;
import java.net.http.HttpRequest.BodyPublisher;
import java.net.http.HttpHeaders;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link HttpRequest}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link HttpRequest} is a completely new class
 * @since 11
 * @see HttpRequest
 */
public final class WhatIsNewInHttpRequest
{
  /**
   * Example call to new method {@link HttpRequest#timeout}
   * @since 11
   * @see HttpRequest#timeout
   */
  public Optional<Duration> timeout()
  {
    HttpRequest testee = $$$();

    Optional<Duration> result = testee.timeout();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#newBuilder}
   * @since 11
   * @see HttpRequest#newBuilder
   */
  public static Builder newBuilder(URI uri)
  {
    Builder result = HttpRequest.newBuilder(uri);
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#newBuilder}
   * @since 11
   * @see HttpRequest#newBuilder
   */
  public static Builder newBuilder()
  {
    Builder result = HttpRequest.newBuilder();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#uri}
   * @since 11
   * @see HttpRequest#uri
   */
  public URI uri()
  {
    HttpRequest testee = $$$();

    URI result = testee.uri();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#version}
   * @since 11
   * @see HttpRequest#version
   */
  public Optional<Version> version()
  {
    HttpRequest testee = $$$();

    Optional<Version> result = testee.version();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#bodyPublisher}
   * @since 11
   * @see HttpRequest#bodyPublisher
   */
  public Optional<BodyPublisher> bodyPublisher()
  {
    HttpRequest testee = $$$();

    Optional<BodyPublisher> result = testee.bodyPublisher();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#method}
   * @since 11
   * @see HttpRequest#method
   */
  public String method()
  {
    HttpRequest testee = $$$();

    String result = testee.method();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#expectContinue}
   * @since 11
   * @see HttpRequest#expectContinue
   */
  public boolean expectContinue()
  {
    HttpRequest testee = $$$();

    boolean result = testee.expectContinue();
    return result;
  }

  /**
   * Example call to new method {@link HttpRequest#headers}
   * @since 11
   * @see HttpRequest#headers
   */
  public HttpHeaders headers()
  {
    HttpRequest testee = $$$();

    HttpHeaders result = testee.headers();
    return result;
  }

  private HttpRequest $$$()
  {
    return null;
  }
}
