package whatisnewin.java.net.http;

import java.net.http.HttpConnectTimeoutException;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link HttpConnectTimeoutException}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link HttpConnectTimeoutException} is a completely new class
 * @since 11
 * @see HttpConnectTimeoutException
 */
public final class WhatIsNewInHttpConnectTimeoutException
{
  /**
   * Example call to new constructor {@link HttpConnectTimeoutException#HttpConnectTimeoutException}
   * @since 11
   * @see HttpConnectTimeoutException#HttpConnectTimeoutException
   */
  public WhatIsNewInHttpConnectTimeoutException(String message)
  {
    HttpConnectTimeoutException testee = new HttpConnectTimeoutException(message);
  }

}
