package whatisnewin.java.net.http;

import java.net.http.WebSocket.Listener;
import java.net.http.WebSocket;
import java.util.concurrent.CompletionStage;
import java.nio.ByteBuffer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Listener}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Listener} is a completely new class.
 * @since 11
 * @see Listener
 */
public final class WhatIsNewInWebSocket$Listener
{
  /**
   * Example call to new method {@link Listener#onOpen(WebSocket)}.
   * @since 11
   * @see Listener#onOpen(WebSocket)
   */
  public void onOpen(WebSocket webSocket)
  {
    Listener testee = $$$();

    testee.onOpen(webSocket);
  }

  /**
   * Example call to new method {@link Listener#onText(WebSocket, CharSequence, boolean)}.
   * @since 11
   * @see Listener#onText(WebSocket, CharSequence, boolean)
   */
  public CompletionStage<?> onText(WebSocket webSocket, CharSequence data, boolean last)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onText(webSocket, data, last);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onBinary(WebSocket, ByteBuffer, boolean)}.
   * @since 11
   * @see Listener#onBinary(WebSocket, ByteBuffer, boolean)
   */
  public CompletionStage<?> onBinary(WebSocket webSocket, ByteBuffer data, boolean last)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onBinary(webSocket, data, last);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onPing(WebSocket, ByteBuffer)}.
   * @since 11
   * @see Listener#onPing(WebSocket, ByteBuffer)
   */
  public CompletionStage<?> onPing(WebSocket webSocket, ByteBuffer message)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onPing(webSocket, message);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onPong(WebSocket, ByteBuffer)}.
   * @since 11
   * @see Listener#onPong(WebSocket, ByteBuffer)
   */
  public CompletionStage<?> onPong(WebSocket webSocket, ByteBuffer message)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onPong(webSocket, message);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onClose(WebSocket, int, String)}.
   * @since 11
   * @see Listener#onClose(WebSocket, int, String)
   */
  public CompletionStage<?> onClose(WebSocket webSocket, int statusCode, String reason)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onClose(webSocket, statusCode, reason);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onError(WebSocket, Throwable)}.
   * @since 11
   * @see Listener#onError(WebSocket, Throwable)
   */
  public void onError(WebSocket webSocket, Throwable error)
  {
    Listener testee = $$$();

    testee.onError(webSocket, error);
  }

  private Listener $$$()
  {
    return null;
  }
}
