package whatisnewin.java.net.http;

import java.net.http.HttpRequest.BodyPublisher;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link BodyPublisher}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link BodyPublisher} is a completely new class
 * @since 11
 * @see BodyPublisher
 */
public final class WhatIsNewInHttpRequest$BodyPublisher
{
  /**
   * Example call to new method {@link BodyPublisher#contentLength}
   * @since 11
   * @see BodyPublisher#contentLength
   */
  public long contentLength()
  {
    BodyPublisher testee = $$$();

    long result = testee.contentLength();
    return result;
  }

  private BodyPublisher $$$()
  {
    return null;
  }
}
