package whatisnewin.java.net.http;

import java.net.http.HttpClient.Version;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Version}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Version} is a completely new class.
 * @since 11
 * @see Version
 */
public final class WhatIsNewInHttpClient$Version
{
  /**
   * Example usage of the new field {@link Version#HTTP_1_1}.
   * @since 11
   * @see Version#HTTP_1_1
   */
  public static final Version HTTP_1_1 = Version.HTTP_1_1;

  /**
   * Example usage of the new field {@link Version#HTTP_2}.
   * @since 11
   * @see Version#HTTP_2
   */
  public static final Version HTTP_2 = Version.HTTP_2;

  /**
   * Example call to new method {@link Version#values()}.
   * @since 11
   * @see Version#values()
   */
  public static Version[] values()
  {
    Version[] result = Version.values();
    return result;
  }

  /**
   * Example call to new method {@link Version#valueOf(String)}.
   * @since 11
   * @see Version#valueOf(String)
   */
  public static Version valueOf(String name)
  {
    Version result = Version.valueOf(name);
    return result;
  }

}
