package whatisnewin.java.net.http;

import java.net.http.WebSocket;
import java.util.concurrent.CompletableFuture;
import java.nio.ByteBuffer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link WebSocket}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link WebSocket} is a completely new class
 * @since 11
 * @see WebSocket
 */
public final class WhatIsNewInWebSocket
{
  /**
   * Example usage of the new field {@link WebSocket#NORMAL_CLOSURE}
   * @since 11
   * @see WebSocket#NORMAL_CLOSURE
   */
  public static  final int NORMAL_CLOSURE = WebSocket.NORMAL_CLOSURE;

  /**
   * Example call to new method {@link WebSocket#request}
   * @since 11
   * @see WebSocket#request
   */
  public void request(long n)
  {
    WebSocket testee = $$$();

    testee.request(n);
  }

  /**
   * Example call to new method {@link WebSocket#sendBinary}
   * @since 11
   * @see WebSocket#sendBinary
   */
  public CompletableFuture<WebSocket> sendBinary(ByteBuffer data, boolean last)
  {
    WebSocket testee = $$$();

    CompletableFuture<WebSocket> result = testee.sendBinary(data, last);
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#sendPing}
   * @since 11
   * @see WebSocket#sendPing
   */
  public CompletableFuture<WebSocket> sendPing(ByteBuffer message)
  {
    WebSocket testee = $$$();

    CompletableFuture<WebSocket> result = testee.sendPing(message);
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#getSubprotocol}
   * @since 11
   * @see WebSocket#getSubprotocol
   */
  public String getSubprotocol()
  {
    WebSocket testee = $$$();

    String result = testee.getSubprotocol();
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#abort}
   * @since 11
   * @see WebSocket#abort
   */
  public void abort()
  {
    WebSocket testee = $$$();

    testee.abort();
  }

  /**
   * Example call to new method {@link WebSocket#isInputClosed}
   * @since 11
   * @see WebSocket#isInputClosed
   */
  public boolean isInputClosed()
  {
    WebSocket testee = $$$();

    boolean result = testee.isInputClosed();
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#sendClose}
   * @since 11
   * @see WebSocket#sendClose
   */
  public CompletableFuture<WebSocket> sendClose(int statusCode, String reason)
  {
    WebSocket testee = $$$();

    CompletableFuture<WebSocket> result = testee.sendClose(statusCode, reason);
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#sendPong}
   * @since 11
   * @see WebSocket#sendPong
   */
  public CompletableFuture<WebSocket> sendPong(ByteBuffer message)
  {
    WebSocket testee = $$$();

    CompletableFuture<WebSocket> result = testee.sendPong(message);
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#isOutputClosed}
   * @since 11
   * @see WebSocket#isOutputClosed
   */
  public boolean isOutputClosed()
  {
    WebSocket testee = $$$();

    boolean result = testee.isOutputClosed();
    return result;
  }

  /**
   * Example call to new method {@link WebSocket#sendText}
   * @since 11
   * @see WebSocket#sendText
   */
  public CompletableFuture<WebSocket> sendText(CharSequence data, boolean last)
  {
    WebSocket testee = $$$();

    CompletableFuture<WebSocket> result = testee.sendText(data, last);
    return result;
  }

  private WebSocket $$$()
  {
    return null;
  }
}
