package whatisnewin.java.net.http;

import java.net.http.WebSocket.Listener;
import java.util.concurrent.CompletionStage;
import java.net.http.WebSocket;
import java.nio.ByteBuffer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Listener}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link Listener} is a completely new class
 * @since 11
 * @see Listener
 */
public final class WhatIsNewInWebSocket$Listener
{
  /**
   * Example call to new method {@link Listener#onPong}
   * @since 11
   * @see Listener#onPong
   */
  public CompletionStage<?> onPong(WebSocket webSocket, ByteBuffer message)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onPong(webSocket, message);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onBinary}
   * @since 11
   * @see Listener#onBinary
   */
  public CompletionStage<?> onBinary(WebSocket webSocket, ByteBuffer data, boolean last)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onBinary(webSocket, data, last);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onPing}
   * @since 11
   * @see Listener#onPing
   */
  public CompletionStage<?> onPing(WebSocket webSocket, ByteBuffer message)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onPing(webSocket, message);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onClose}
   * @since 11
   * @see Listener#onClose
   */
  public CompletionStage<?> onClose(WebSocket webSocket, int statusCode, String reason)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onClose(webSocket, statusCode, reason);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onText}
   * @since 11
   * @see Listener#onText
   */
  public CompletionStage<?> onText(WebSocket webSocket, CharSequence data, boolean last)
  {
    Listener testee = $$$();

    CompletionStage<?> result = testee.onText(webSocket, data, last);
    return result;
  }

  /**
   * Example call to new method {@link Listener#onError}
   * @since 11
   * @see Listener#onError
   */
  public void onError(WebSocket webSocket, Throwable error)
  {
    Listener testee = $$$();

    testee.onError(webSocket, error);
  }

  /**
   * Example call to new method {@link Listener#onOpen}
   * @since 11
   * @see Listener#onOpen
   */
  public void onOpen(WebSocket webSocket)
  {
    Listener testee = $$$();

    testee.onOpen(webSocket);
  }

  private Listener $$$()
  {
    return null;
  }
}
