package whatisnewin.java.net.http;

import java.net.http.HttpTimeoutException;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link HttpTimeoutException}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link HttpTimeoutException} is a completely new class
 * @since 11
 * @see HttpTimeoutException
 */
public final class WhatIsNewInHttpTimeoutException
{
  /**
   * Example call to new constructor {@link HttpTimeoutException#HttpTimeoutException}
   * @since 11
   * @see HttpTimeoutException#HttpTimeoutException
   */
  public WhatIsNewInHttpTimeoutException(String message)
  {
    HttpTimeoutException testee = new HttpTimeoutException(message);
  }

}
