package whatisnewin.java.net.http;

import java.net.http.HttpResponse.ResponseInfo;
import java.net.http.HttpHeaders;
import java.net.http.HttpClient.Version;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ResponseInfo}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link ResponseInfo} is a completely new class.
 * @since 11
 * @see ResponseInfo
 */
public final class WhatIsNewInHttpResponse$ResponseInfo
{
  /**
   * Example call to new method {@link ResponseInfo#statusCode()}.
   * @since 11
   * @see ResponseInfo#statusCode()
   */
  public int statusCode()
  {
    ResponseInfo testee = $$$();

    int result = testee.statusCode();
    return result;
  }

  /**
   * Example call to new method {@link ResponseInfo#headers()}.
   * @since 11
   * @see ResponseInfo#headers()
   */
  public HttpHeaders headers()
  {
    ResponseInfo testee = $$$();

    HttpHeaders result = testee.headers();
    return result;
  }

  /**
   * Example call to new method {@link ResponseInfo#version()}.
   * @since 11
   * @see ResponseInfo#version()
   */
  public Version version()
  {
    ResponseInfo testee = $$$();

    Version result = testee.version();
    return result;
  }

  private ResponseInfo $$$()
  {
    return null;
  }
}
