package whatisnewin.java.net.http;

import java.net.http.WebSocketHandshakeException;
import java.net.http.HttpResponse;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link WebSocketHandshakeException}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link WebSocketHandshakeException} is a completely new class.
 * @since 11
 * @see WebSocketHandshakeException
 */
public final class WhatIsNewInWebSocketHandshakeException
{
  /**
   * Example call to new constructor {@link WebSocketHandshakeException#WebSocketHandshakeException(HttpResponse)}.
   * @since 11
   * @see WebSocketHandshakeException#WebSocketHandshakeException(HttpResponse)
   */
  public WhatIsNewInWebSocketHandshakeException(HttpResponse<?> response)
  {
    WebSocketHandshakeException testee = new WebSocketHandshakeException(response);
  }

  /**
   * Example call to new method {@link WebSocketHandshakeException#getResponse()}.
   * @since 11
   * @see WebSocketHandshakeException#getResponse()
   */
  public HttpResponse<?> getResponse()
  {
    WebSocketHandshakeException testee = $$$();

    HttpResponse<?> result = testee.getResponse();
    return result;
  }

  /**
   * Example call to new method {@link WebSocketHandshakeException#initCause(Throwable)}.
   * @since 11
   * @see WebSocketHandshakeException#initCause(Throwable)
   */
  public WebSocketHandshakeException initCause(Throwable cause)
  {
    WebSocketHandshakeException testee = $$$();

    WebSocketHandshakeException result = testee.initCause(cause);
    return result;
  }

  private WebSocketHandshakeException $$$()
  {
    return null;
  }
}
