package whatisnewin.java.net.http;

import java.net.http.HttpClient.Redirect;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Redirect}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Redirect} is a completely new class.
 * @since 11
 * @see Redirect
 */
public final class WhatIsNewInHttpClient$Redirect
{
  /**
   * Example usage of the new field {@link Redirect#NEVER}.
   * @since 11
   * @see Redirect#NEVER
   */
  public static final Redirect NEVER = Redirect.NEVER;

  /**
   * Example usage of the new field {@link Redirect#ALWAYS}.
   * @since 11
   * @see Redirect#ALWAYS
   */
  public static final Redirect ALWAYS = Redirect.ALWAYS;

  /**
   * Example usage of the new field {@link Redirect#NORMAL}.
   * @since 11
   * @see Redirect#NORMAL
   */
  public static final Redirect NORMAL = Redirect.NORMAL;

  /**
   * Example call to new method {@link Redirect#values()}.
   * @since 11
   * @see Redirect#values()
   */
  public static Redirect[] values()
  {
    Redirect[] result = Redirect.values();
    return result;
  }

  /**
   * Example call to new method {@link Redirect#valueOf(String)}.
   * @since 11
   * @see Redirect#valueOf(String)
   */
  public static Redirect valueOf(String name)
  {
    Redirect result = Redirect.valueOf(name);
    return result;
  }

}
