package whatisnewin.javax.crypto.spec;

import javax.crypto.spec.ChaCha20ParameterSpec;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ChaCha20ParameterSpec}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link ChaCha20ParameterSpec} is a completely new class
 * @since 11
 * @see ChaCha20ParameterSpec
 */
public final class WhatIsNewInChaCha20ParameterSpec
{
  /**
   * Example call to new constructor {@link ChaCha20ParameterSpec#ChaCha20ParameterSpec}
   * @since 11
   * @see ChaCha20ParameterSpec#ChaCha20ParameterSpec
   */
  public WhatIsNewInChaCha20ParameterSpec(byte[] nonce, int counter)
  {
    ChaCha20ParameterSpec testee = new ChaCha20ParameterSpec(nonce, counter);
  }

  /**
   * Example call to new method {@link ChaCha20ParameterSpec#getNonce}
   * @since 11
   * @see ChaCha20ParameterSpec#getNonce
   */
  public byte[] getNonce()
  {
    ChaCha20ParameterSpec testee = $$$();

    byte[] result = testee.getNonce();
    return result;
  }

  /**
   * Example call to new method {@link ChaCha20ParameterSpec#getCounter}
   * @since 11
   * @see ChaCha20ParameterSpec#getCounter
   */
  public int getCounter()
  {
    ChaCha20ParameterSpec testee = $$$();

    int result = testee.getCounter();
    return result;
  }

  private ChaCha20ParameterSpec $$$()
  {
    return null;
  }
}
