package whatisnewin.java.util.zip;

import java.util.zip.Deflater;
import java.nio.ByteBuffer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Deflater}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link Deflater} is an old class but has new fields, constructors or methods
 * @since 1.1
 * @see Deflater
 */
public final class WhatIsNewInDeflater
{
  /**
   * Example call to new method {@link Deflater#setInput}
   * @since 11
   * @see Deflater#setInput
   */
  public void setInput(ByteBuffer input)
  {
    Deflater testee = $$$();

    testee.setInput(input);
  }

  /**
   * Example call to new method {@link Deflater#deflate}
   * @since 11
   * @see Deflater#deflate
   */
  public int deflate(ByteBuffer output)
  {
    Deflater testee = $$$();

    int result = testee.deflate(output);
    return result;
  }

  /**
   * Example call to new method {@link Deflater#deflate}
   * @since 11
   * @see Deflater#deflate
   */
  public int deflate(ByteBuffer output, int flush)
  {
    Deflater testee = $$$();

    int result = testee.deflate(output, flush);
    return result;
  }

  private Deflater $$$()
  {
    return null;
  }
}
