package whatisnewin.java.security.spec;

import java.security.spec.RSAPrivateKeySpec;
import java.math.BigInteger;
import java.security.spec.AlgorithmParameterSpec;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RSAPrivateKeySpec}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link RSAPrivateKeySpec} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see RSAPrivateKeySpec
 */
public final class WhatIsNewInRSAPrivateKeySpec
{
  /**
   * Example call to new constructor {@link RSAPrivateKeySpec#RSAPrivateKeySpec(BigInteger, BigInteger, AlgorithmParameterSpec)}.
   * @since 11
   * @see RSAPrivateKeySpec#RSAPrivateKeySpec(BigInteger, BigInteger, AlgorithmParameterSpec)
   */
  public WhatIsNewInRSAPrivateKeySpec(BigInteger modulus, BigInteger privateExponent, AlgorithmParameterSpec params)
  {
    RSAPrivateKeySpec testee = new RSAPrivateKeySpec(modulus, privateExponent, params);
  }

  /**
   * Example call to new method {@link RSAPrivateKeySpec#getParams()}.
   * @since 11
   * @see RSAPrivateKeySpec#getParams()
   */
  public AlgorithmParameterSpec getParams()
  {
    RSAPrivateKeySpec testee = $$$();

    AlgorithmParameterSpec result = testee.getParams();
    return result;
  }

  private RSAPrivateKeySpec $$$()
  {
    return null;
  }
}
