package whatisnewin.java.security.spec;

import java.security.spec.PSSParameterSpec;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link PSSParameterSpec}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link PSSParameterSpec} is an old class but has new fields, constructors or methods
 * @since 1.4
 * @see PSSParameterSpec
 */
public final class WhatIsNewInPSSParameterSpec
{
  /**
   * Example usage of the new field {@link PSSParameterSpec#TRAILER_FIELD_BC}
   * @since 11
   * @see PSSParameterSpec#TRAILER_FIELD_BC
   */
  public static  final int TRAILER_FIELD_BC = PSSParameterSpec.TRAILER_FIELD_BC;

}
