package whatisnewin.java.security.spec;

import java.security.spec.XECPrivateKeySpec;
import java.security.spec.AlgorithmParameterSpec;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link XECPrivateKeySpec}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link XECPrivateKeySpec} is a completely new class
 * @since 11
 * @see XECPrivateKeySpec
 */
public final class WhatIsNewInXECPrivateKeySpec
{
  /**
   * Example call to new constructor {@link XECPrivateKeySpec#XECPrivateKeySpec}
   * @since 11
   * @see XECPrivateKeySpec#XECPrivateKeySpec
   */
  public WhatIsNewInXECPrivateKeySpec(AlgorithmParameterSpec params, byte[] scalar)
  {
    XECPrivateKeySpec testee = new XECPrivateKeySpec(params, scalar);
  }

  /**
   * Example call to new method {@link XECPrivateKeySpec#getParams}
   * @since 11
   * @see XECPrivateKeySpec#getParams
   */
  public AlgorithmParameterSpec getParams()
  {
    XECPrivateKeySpec testee = $$$();

    AlgorithmParameterSpec result = testee.getParams();
    return result;
  }

  /**
   * Example call to new method {@link XECPrivateKeySpec#getScalar}
   * @since 11
   * @see XECPrivateKeySpec#getScalar
   */
  public byte[] getScalar()
  {
    XECPrivateKeySpec testee = $$$();

    byte[] result = testee.getScalar();
    return result;
  }

  private XECPrivateKeySpec $$$()
  {
    return null;
  }
}
