package whatisnewin.java.security.spec;

import java.security.spec.RSAPublicKeySpec;
import java.math.BigInteger;
import java.security.spec.AlgorithmParameterSpec;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link RSAPublicKeySpec}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link RSAPublicKeySpec} is an old class but has new fields, constructors or methods
 * @since 1.2
 * @see RSAPublicKeySpec
 */
public final class WhatIsNewInRSAPublicKeySpec
{
  /**
   * Example call to new constructor {@link RSAPublicKeySpec#RSAPublicKeySpec}
   * @since 11
   * @see RSAPublicKeySpec#RSAPublicKeySpec
   */
  public WhatIsNewInRSAPublicKeySpec(BigInteger modulus, BigInteger publicExponent, AlgorithmParameterSpec params)
  {
    RSAPublicKeySpec testee = new RSAPublicKeySpec(modulus, publicExponent, params);
  }

}
