package whatisnewin.java.io;

import java.io.Reader;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Reader}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Reader} is an old class but has new fields, constructors or methods.
 * @since 1.1
 * @see Reader
 */
public final class WhatIsNewInReader
{
  /**
   * Example call to new method {@link Reader#nullReader()}.
   * @since 11
   * @see Reader#nullReader()
   */
  public static Reader nullReader()
  {
    Reader result = Reader.nullReader();
    return result;
  }

}
