package whatisnewin.java.io;

import java.io.FileReader;
import java.nio.charset.Charset;
import java.io.IOException;
import java.io.File;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link FileReader}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link FileReader} is an old class but has new fields, constructors or methods.
 * @since 1.1
 * @see FileReader
 */
public final class WhatIsNewInFileReader
{
  /**
   * Example call to new constructor {@link FileReader#FileReader(String, Charset)}.
   * @since 11
   * @see FileReader#FileReader(String, Charset)
   */
  public WhatIsNewInFileReader(String fileName, Charset charset) throws IOException
  {
    FileReader testee = new FileReader(fileName, charset);
  }

  /**
   * Example call to new constructor {@link FileReader#FileReader(File, Charset)}.
   * @since 11
   * @see FileReader#FileReader(File, Charset)
   */
  public WhatIsNewInFileReader(File file, Charset charset) throws IOException
  {
    FileReader testee = new FileReader(file, charset);
  }

}
