package whatisnewin.java.io;

import java.io.ByteArrayOutputStream;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ByteArrayOutputStream}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link ByteArrayOutputStream} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see ByteArrayOutputStream
 */
public final class WhatIsNewInByteArrayOutputStream
{
  /**
   * Example call to new method {@link ByteArrayOutputStream#writeBytes(byte[])}.
   * @since 11
   * @see ByteArrayOutputStream#writeBytes(byte[])
   */
  public void writeBytes(byte[] b)
  {
    ByteArrayOutputStream testee = $$$();

    testee.writeBytes(b);
  }

  private ByteArrayOutputStream $$$()
  {
    return null;
  }
}
