package whatisnewin.java.io;

import java.io.Writer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Writer}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link Writer} is an old class but has new fields, constructors or methods
 * @since 1.1
 * @see Writer
 */
public final class WhatIsNewInWriter
{
  /**
   * Example call to new method {@link Writer#nullWriter}
   * @since 11
   * @see Writer#nullWriter
   */
  public static Writer nullWriter()
  {
    Writer result = Writer.nullWriter();
    return result;
  }

}
