package whatisnewin.java.io;

import java.io.FileWriter;
import java.nio.charset.Charset;
import java.io.IOException;
import java.io.File;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link FileWriter}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link FileWriter} is an old class but has new fields, constructors or methods.
 * @since 1.1
 * @see FileWriter
 */
public final class WhatIsNewInFileWriter
{
  /**
   * Example call to new constructor {@link FileWriter#FileWriter(String, Charset)}.
   * @since 11
   * @see FileWriter#FileWriter(String, Charset)
   */
  public WhatIsNewInFileWriter(String fileName, Charset charset) throws IOException
  {
    FileWriter testee = new FileWriter(fileName, charset);
  }

  /**
   * Example call to new constructor {@link FileWriter#FileWriter(String, Charset, boolean)}.
   * @since 11
   * @see FileWriter#FileWriter(String, Charset, boolean)
   */
  public WhatIsNewInFileWriter(String fileName, Charset charset, boolean append) throws IOException
  {
    FileWriter testee = new FileWriter(fileName, charset, append);
  }

  /**
   * Example call to new constructor {@link FileWriter#FileWriter(File, Charset)}.
   * @since 11
   * @see FileWriter#FileWriter(File, Charset)
   */
  public WhatIsNewInFileWriter(File file, Charset charset) throws IOException
  {
    FileWriter testee = new FileWriter(file, charset);
  }

}
