package whatisnewin.java.io;

import java.io.OutputStream;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OutputStream}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link OutputStream} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see OutputStream
 */
public final class WhatIsNewInOutputStream
{
  /**
   * Example call to new method {@link OutputStream#nullOutputStream()}.
   * @since 11
   * @see OutputStream#nullOutputStream()
   */
  public static OutputStream nullOutputStream()
  {
    OutputStream result = OutputStream.nullOutputStream();
    return result;
  }

}
