package whatisnewin.java.util.concurrent;

import java.util.concurrent.TimeUnit;
import java.time.Duration;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link TimeUnit}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link TimeUnit} is an old class but has new fields, constructors or methods
 * @since 1.5
 * @see TimeUnit
 */
public final class WhatIsNewInTimeUnit
{
  /**
   * Example call to new method {@link TimeUnit#convert}
   * @since 11
   * @see TimeUnit#convert
   */
  public long convert(Duration duration)
  {
    TimeUnit testee = $$$();

    long result = testee.convert(duration);
    return result;
  }

  private TimeUnit $$$()
  {
    return null;
  }
}
