package whatisnewin.java.util.regex;

import java.util.regex.Pattern;
import java.util.function.Predicate;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Pattern}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link Pattern} is an old class but has new fields, constructors or methods
 * @since 1.4
 * @see Pattern
 */
public final class WhatIsNewInPattern
{
  /**
   * Example call to new method {@link Pattern#asMatchPredicate}
   * @since 11
   * @see Pattern#asMatchPredicate
   */
  public Predicate<String> asMatchPredicate()
  {
    Pattern testee = $$$();

    Predicate<String> result = testee.asMatchPredicate();
    return result;
  }

  private Pattern $$$()
  {
    return null;
  }
}
