package whatisnewin.java.security.interfaces;

import java.security.interfaces.XECPrivateKey;
import java.util.Optional;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link XECPrivateKey}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link XECPrivateKey} is a completely new class.
 * @since 11
 * @see XECPrivateKey
 */
public final class WhatIsNewInXECPrivateKey
{
  /**
   * Example call to new method {@link XECPrivateKey#getScalar()}.
   * @since 11
   * @see XECPrivateKey#getScalar()
   */
  public Optional<byte[]> getScalar()
  {
    XECPrivateKey testee = $$$();

    Optional<byte[]> result = testee.getScalar();
    return result;
  }

  private XECPrivateKey $$$()
  {
    return null;
  }
}
