package whatisnewin.java.security.interfaces;

import java.security.interfaces.RSAKey;
import java.security.spec.AlgorithmParameterSpec;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RSAKey}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link RSAKey} is an old class but has new fields, constructors or methods.
 * @since 1.3
 * @see RSAKey
 */
public final class WhatIsNewInRSAKey
{
  /**
   * Example call to new method {@link RSAKey#getParams()}.
   * @since 11
   * @see RSAKey#getParams()
   */
  public AlgorithmParameterSpec getParams()
  {
    RSAKey testee = $$$();

    AlgorithmParameterSpec result = testee.getParams();
    return result;
  }

  private RSAKey $$$()
  {
    return null;
  }
}
