package whatisnewin.java.security.interfaces;

import java.security.interfaces.XECPublicKey;
import java.math.BigInteger;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link XECPublicKey}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link XECPublicKey} is a completely new class
 * @since 11
 * @see XECPublicKey
 */
public final class WhatIsNewInXECPublicKey
{
  /**
   * Example call to new method {@link XECPublicKey#getU}
   * @since 11
   * @see XECPublicKey#getU
   */
  public BigInteger getU()
  {
    XECPublicKey testee = $$$();

    BigInteger result = testee.getU();
    return result;
  }

  private XECPublicKey $$$()
  {
    return null;
  }
}
