package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Character}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Character} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Character
 */
public final class WhatIsNewInCharacter
{
  /**
   * Example call to new method {@link Character#toString(int)}.
   * @since 11
   * @see Character#toString(int)
   */
  public static String toString(int codePoint)
  {
    String result = Character.toString(codePoint);
    return result;
  }

}
