package whatisnewin.java.lang;

import java.lang.Character.UnicodeScript;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link UnicodeScript}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link UnicodeScript} is an old class but has new fields, constructors or methods
 * @since 1.7
 * @see UnicodeScript
 */
public final class WhatIsNewInCharacter$UnicodeScript
{
  /**
   * Example usage of the new field {@link UnicodeScript#ADLAM}
   * @since 11
   * @see UnicodeScript#ADLAM
   */
  public static  final UnicodeScript ADLAM = UnicodeScript.ADLAM;

  /**
   * Example usage of the new field {@link UnicodeScript#BHAIKSUKI}
   * @since 11
   * @see UnicodeScript#BHAIKSUKI
   */
  public static  final UnicodeScript BHAIKSUKI = UnicodeScript.BHAIKSUKI;

  /**
   * Example usage of the new field {@link UnicodeScript#MARCHEN}
   * @since 11
   * @see UnicodeScript#MARCHEN
   */
  public static  final UnicodeScript MARCHEN = UnicodeScript.MARCHEN;

  /**
   * Example usage of the new field {@link UnicodeScript#NEWA}
   * @since 11
   * @see UnicodeScript#NEWA
   */
  public static  final UnicodeScript NEWA = UnicodeScript.NEWA;

  /**
   * Example usage of the new field {@link UnicodeScript#OSAGE}
   * @since 11
   * @see UnicodeScript#OSAGE
   */
  public static  final UnicodeScript OSAGE = UnicodeScript.OSAGE;

  /**
   * Example usage of the new field {@link UnicodeScript#TANGUT}
   * @since 11
   * @see UnicodeScript#TANGUT
   */
  public static  final UnicodeScript TANGUT = UnicodeScript.TANGUT;

  /**
   * Example usage of the new field {@link UnicodeScript#MASARAM_GONDI}
   * @since 11
   * @see UnicodeScript#MASARAM_GONDI
   */
  public static  final UnicodeScript MASARAM_GONDI = UnicodeScript.MASARAM_GONDI;

  /**
   * Example usage of the new field {@link UnicodeScript#NUSHU}
   * @since 11
   * @see UnicodeScript#NUSHU
   */
  public static  final UnicodeScript NUSHU = UnicodeScript.NUSHU;

  /**
   * Example usage of the new field {@link UnicodeScript#SOYOMBO}
   * @since 11
   * @see UnicodeScript#SOYOMBO
   */
  public static  final UnicodeScript SOYOMBO = UnicodeScript.SOYOMBO;

  /**
   * Example usage of the new field {@link UnicodeScript#ZANABAZAR_SQUARE}
   * @since 11
   * @see UnicodeScript#ZANABAZAR_SQUARE
   */
  public static  final UnicodeScript ZANABAZAR_SQUARE = UnicodeScript.ZANABAZAR_SQUARE;

}
