package whatisnewin.java.lang;

import java.lang.Character.UnicodeBlock;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link UnicodeBlock}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link UnicodeBlock} is an old class but has new fields, constructors or methods
 * @since 1.2
 * @see UnicodeBlock
 */
public final class WhatIsNewInCharacter$UnicodeBlock
{
  /**
   * Example usage of the new field {@link UnicodeBlock#SYRIAC_SUPPLEMENT}
   * @since 11
   * @see UnicodeBlock#SYRIAC_SUPPLEMENT
   */
  public static  final UnicodeBlock SYRIAC_SUPPLEMENT = UnicodeBlock.SYRIAC_SUPPLEMENT;

  /**
   * Example usage of the new field {@link UnicodeBlock#CYRILLIC_EXTENDED_C}
   * @since 11
   * @see UnicodeBlock#CYRILLIC_EXTENDED_C
   */
  public static  final UnicodeBlock CYRILLIC_EXTENDED_C = UnicodeBlock.CYRILLIC_EXTENDED_C;

  /**
   * Example usage of the new field {@link UnicodeBlock#OSAGE}
   * @since 11
   * @see UnicodeBlock#OSAGE
   */
  public static  final UnicodeBlock OSAGE = UnicodeBlock.OSAGE;

  /**
   * Example usage of the new field {@link UnicodeBlock#NEWA}
   * @since 11
   * @see UnicodeBlock#NEWA
   */
  public static  final UnicodeBlock NEWA = UnicodeBlock.NEWA;

  /**
   * Example usage of the new field {@link UnicodeBlock#MONGOLIAN_SUPPLEMENT}
   * @since 11
   * @see UnicodeBlock#MONGOLIAN_SUPPLEMENT
   */
  public static  final UnicodeBlock MONGOLIAN_SUPPLEMENT = UnicodeBlock.MONGOLIAN_SUPPLEMENT;

  /**
   * Example usage of the new field {@link UnicodeBlock#MARCHEN}
   * @since 11
   * @see UnicodeBlock#MARCHEN
   */
  public static  final UnicodeBlock MARCHEN = UnicodeBlock.MARCHEN;

  /**
   * Example usage of the new field {@link UnicodeBlock#IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION}
   * @since 11
   * @see UnicodeBlock#IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION
   */
  public static  final UnicodeBlock IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION = UnicodeBlock.IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION;

  /**
   * Example usage of the new field {@link UnicodeBlock#TANGUT}
   * @since 11
   * @see UnicodeBlock#TANGUT
   */
  public static  final UnicodeBlock TANGUT = UnicodeBlock.TANGUT;

  /**
   * Example usage of the new field {@link UnicodeBlock#TANGUT_COMPONENTS}
   * @since 11
   * @see UnicodeBlock#TANGUT_COMPONENTS
   */
  public static  final UnicodeBlock TANGUT_COMPONENTS = UnicodeBlock.TANGUT_COMPONENTS;

  /**
   * Example usage of the new field {@link UnicodeBlock#KANA_EXTENDED_A}
   * @since 11
   * @see UnicodeBlock#KANA_EXTENDED_A
   */
  public static  final UnicodeBlock KANA_EXTENDED_A = UnicodeBlock.KANA_EXTENDED_A;

  /**
   * Example usage of the new field {@link UnicodeBlock#GLAGOLITIC_SUPPLEMENT}
   * @since 11
   * @see UnicodeBlock#GLAGOLITIC_SUPPLEMENT
   */
  public static  final UnicodeBlock GLAGOLITIC_SUPPLEMENT = UnicodeBlock.GLAGOLITIC_SUPPLEMENT;

  /**
   * Example usage of the new field {@link UnicodeBlock#ADLAM}
   * @since 11
   * @see UnicodeBlock#ADLAM
   */
  public static  final UnicodeBlock ADLAM = UnicodeBlock.ADLAM;

  /**
   * Example usage of the new field {@link UnicodeBlock#MASARAM_GONDI}
   * @since 11
   * @see UnicodeBlock#MASARAM_GONDI
   */
  public static  final UnicodeBlock MASARAM_GONDI = UnicodeBlock.MASARAM_GONDI;

  /**
   * Example usage of the new field {@link UnicodeBlock#ZANABAZAR_SQUARE}
   * @since 11
   * @see UnicodeBlock#ZANABAZAR_SQUARE
   */
  public static  final UnicodeBlock ZANABAZAR_SQUARE = UnicodeBlock.ZANABAZAR_SQUARE;

  /**
   * Example usage of the new field {@link UnicodeBlock#NUSHU}
   * @since 11
   * @see UnicodeBlock#NUSHU
   */
  public static  final UnicodeBlock NUSHU = UnicodeBlock.NUSHU;

  /**
   * Example usage of the new field {@link UnicodeBlock#SOYOMBO}
   * @since 11
   * @see UnicodeBlock#SOYOMBO
   */
  public static  final UnicodeBlock SOYOMBO = UnicodeBlock.SOYOMBO;

  /**
   * Example usage of the new field {@link UnicodeBlock#BHAIKSUKI}
   * @since 11
   * @see UnicodeBlock#BHAIKSUKI
   */
  public static  final UnicodeBlock BHAIKSUKI = UnicodeBlock.BHAIKSUKI;

  /**
   * Example usage of the new field {@link UnicodeBlock#CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F}
   * @since 11
   * @see UnicodeBlock#CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F
   */
  public static  final UnicodeBlock CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F = UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F;

}
