package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link StringBuilder}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link StringBuilder} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see StringBuilder
 */
public final class WhatIsNewInStringBuilder
{
  /**
   * Example call to new method {@link StringBuilder#compareTo(StringBuilder)}.
   * @since 11
   * @see StringBuilder#compareTo(StringBuilder)
   */
  public int compareTo(StringBuilder another)
  {
    StringBuilder testee = $$$();

    int result = testee.compareTo(another);
    return result;
  }

  private StringBuilder $$$()
  {
    return null;
  }
}
