package whatisnewin.java.lang;

import java.util.stream.Stream;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link String}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link String} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see String
 */
public final class WhatIsNewInString
{
  /**
   * Example call to new method {@link String#strip()}.
   * @since 11
   * @see String#strip()
   */
  public String strip()
  {
    String testee = $$$();

    String result = testee.strip();
    return result;
  }

  /**
   * Example call to new method {@link String#isBlank()}.
   * @since 11
   * @see String#isBlank()
   */
  public boolean isBlank()
  {
    String testee = $$$();

    boolean result = testee.isBlank();
    return result;
  }

  /**
   * Example call to new method {@link String#stripTrailing()}.
   * @since 11
   * @see String#stripTrailing()
   */
  public String stripTrailing()
  {
    String testee = $$$();

    String result = testee.stripTrailing();
    return result;
  }

  /**
   * Example call to new method {@link String#repeat(int)}.
   * @since 11
   * @see String#repeat(int)
   */
  public String repeat(int count)
  {
    String testee = $$$();

    String result = testee.repeat(count);
    return result;
  }

  /**
   * Example call to new method {@link String#stripLeading()}.
   * @since 11
   * @see String#stripLeading()
   */
  public String stripLeading()
  {
    String testee = $$$();

    String result = testee.stripLeading();
    return result;
  }

  /**
   * Example call to new method {@link String#lines()}.
   * @since 11
   * @see String#lines()
   */
  public Stream<String> lines()
  {
    String testee = $$$();

    Stream<String> result = testee.lines();
    return result;
  }

  private String $$$()
  {
    return null;
  }
}
