package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Class}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link Class} is an old class but has new fields, constructors or methods
 * @since 1.0
 * @see Class
 */
public final class WhatIsNewInClass<T>
{
  /**
   * Example call to new method {@link Class#isNestmateOf}
   * @since 11
   * @see Class#isNestmateOf
   */
  public boolean isNestmateOf(Class<?> c)
  {
    Class<T> testee = $$$();

    boolean result = testee.isNestmateOf(c);
    return result;
  }

  /**
   * Example call to new method {@link Class#getNestHost}
   * @since 11
   * @see Class#getNestHost
   */
  public Class<?> getNestHost()
  {
    Class<T> testee = $$$();

    Class<?> result = testee.getNestHost();
    return result;
  }

  /**
   * Example call to new method {@link Class#getNestMembers}
   * @since 11
   * @see Class#getNestMembers
   */
  public Class<?>[] getNestMembers()
  {
    Class<T> testee = $$$();

    Class<?>[] result = testee.getNestMembers();
    return result;
  }

  private Class $$$()
  {
    return null;
  }
}
