package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link CharSequence}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link CharSequence} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see CharSequence
 */
public final class WhatIsNewInCharSequence
{
  /**
   * Example call to new method {@link CharSequence#compare(CharSequence, CharSequence)}.
   * @since 11
   * @see CharSequence#compare(CharSequence, CharSequence)
   */
  public static int compare(CharSequence cs1, CharSequence cs2)
  {
    int result = CharSequence.compare(cs1, cs2);
    return result;
  }

}
