package whatisnewin.java.nio;

import java.nio.IntBuffer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link IntBuffer}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link IntBuffer} is an old class but has new fields, constructors or methods
 * @since 1.4
 * @see IntBuffer
 */
public final class WhatIsNewInIntBuffer
{
  /**
   * Example call to new method {@link IntBuffer#mismatch}
   * @since 11
   * @see IntBuffer#mismatch
   */
  public int mismatch(IntBuffer that)
  {
    IntBuffer testee = $$$();

    int result = testee.mismatch(that);
    return result;
  }

  private IntBuffer $$$()
  {
    return null;
  }
}
