package whatisnewin.java.nio;

import java.nio.CharBuffer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link CharBuffer}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link CharBuffer} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see CharBuffer
 */
public final class WhatIsNewInCharBuffer
{
  /**
   * Example call to new method {@link CharBuffer#mismatch(CharBuffer)}.
   * @since 11
   * @see CharBuffer#mismatch(CharBuffer)
   */
  public int mismatch(CharBuffer that)
  {
    CharBuffer testee = $$$();

    int result = testee.mismatch(that);
    return result;
  }

  private CharBuffer $$$()
  {
    return null;
  }
}
