package whatisnewin.java.nio.file;

import java.nio.file.Path;
import java.net.URI;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Path}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link Path} is an old class but has new fields, constructors or methods
 * @since 1.7
 * @see Path
 */
public final class WhatIsNewInPath
{
  /**
   * Example call to new method {@link Path#of}
   * @since 11
   * @see Path#of
   */
  public static Path of(String first, String[] more)
  {
    Path result = Path.of(first, more);
    return result;
  }

  /**
   * Example call to new method {@link Path#of}
   * @since 11
   * @see Path#of
   */
  public static Path of(URI uri)
  {
    Path result = Path.of(uri);
    return result;
  }

}
