package whatisnewin.jdk.nio;

import jdk.nio.Channels;
import java.nio.channels.SelectableChannel;
import java.io.FileDescriptor;
import jdk.nio.Channels.SelectableChannelCloser;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Channels}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Channels} is a completely new class.
 * @since 11
 * @see Channels
 */
public final class WhatIsNewInChannels
{
  /**
   * Example call to new method {@link Channels#readWriteSelectableChannel(FileDescriptor, SelectableChannelCloser)}.
   * @since 11
   * @see Channels#readWriteSelectableChannel(FileDescriptor, SelectableChannelCloser)
   */
  public static SelectableChannel readWriteSelectableChannel(FileDescriptor fd, SelectableChannelCloser closer)
  {
    SelectableChannel result = Channels.readWriteSelectableChannel(fd, closer);
    return result;
  }

}
