package whatisnewin.java.lang.ref;

import java.lang.ref.Reference;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Reference}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Reference} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see Reference
 */
public final class WhatIsNewInReference<T>
{
}
