package whatisnewin.java.util;

import java.util.Optional;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Optional}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link Optional} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see Optional
 */
public final class WhatIsNewInOptional<T>
{
  /**
   * Example call to new method {@link Optional#isEmpty()}.
   * @since 11
   * @see Optional#isEmpty()
   */
  public boolean isEmpty()
  {
    Optional<T> testee = $$$();

    boolean result = testee.isEmpty();
    return result;
  }

  private Optional<T> $$$()
  {
    return null;
  }
}
