package whatisnewin.java.util;

import java.util.OptionalDouble;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link OptionalDouble}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link OptionalDouble} is an old class but has new fields, constructors or methods
 * @since 1.8
 * @see OptionalDouble
 */
public final class WhatIsNewInOptionalDouble
{
  /**
   * Example call to new method {@link OptionalDouble#isEmpty}
   * @since 11
   * @see OptionalDouble#isEmpty
   */
  public boolean isEmpty()
  {
    OptionalDouble testee = $$$();

    boolean result = testee.isEmpty();
    return result;
  }

  private OptionalDouble $$$()
  {
    return null;
  }
}
