package whatisnewin.java.util;

import java.util.OptionalLong;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OptionalLong}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link OptionalLong} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see OptionalLong
 */
public final class WhatIsNewInOptionalLong
{
  /**
   * Example call to new method {@link OptionalLong#isEmpty()}.
   * @since 11
   * @see OptionalLong#isEmpty()
   */
  public boolean isEmpty()
  {
    OptionalLong testee = $$$();

    boolean result = testee.isEmpty();
    return result;
  }

  private OptionalLong $$$()
  {
    return null;
  }
}
