package whatisnewin.java.util;

import java.util.OptionalInt;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link OptionalInt}
 * that were newly introduced in Java versions 11.<br>
 *
 * {@link OptionalInt} is an old class but has new fields, constructors or methods
 * @since 1.8
 * @see OptionalInt
 */
public final class WhatIsNewInOptionalInt
{
  /**
   * Example call to new method {@link OptionalInt#isEmpty}
   * @since 11
   * @see OptionalInt#isEmpty
   */
  public boolean isEmpty()
  {
    OptionalInt testee = $$$();

    boolean result = testee.isEmpty();
    return result;
  }

  private OptionalInt $$$()
  {
    return null;
  }
}
