package whatisnewin.javax.xml.crypto.dsig;

import javax.xml.crypto.dsig.SignatureMethod;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SignatureMethod}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link SignatureMethod} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see SignatureMethod
 */
public final class WhatIsNewInSignatureMethod
{
  /**
   * Example usage of the new field {@link SignatureMethod#DSA_SHA256}.
   * @since 11
   * @see SignatureMethod#DSA_SHA256
   */
  public static final String DSA_SHA256 = SignatureMethod.DSA_SHA256;

  /**
   * Example usage of the new field {@link SignatureMethod#RSA_SHA224}.
   * @since 11
   * @see SignatureMethod#RSA_SHA224
   */
  public static final String RSA_SHA224 = SignatureMethod.RSA_SHA224;

  /**
   * Example usage of the new field {@link SignatureMethod#RSA_SHA256}.
   * @since 11
   * @see SignatureMethod#RSA_SHA256
   */
  public static final String RSA_SHA256 = SignatureMethod.RSA_SHA256;

  /**
   * Example usage of the new field {@link SignatureMethod#RSA_SHA384}.
   * @since 11
   * @see SignatureMethod#RSA_SHA384
   */
  public static final String RSA_SHA384 = SignatureMethod.RSA_SHA384;

  /**
   * Example usage of the new field {@link SignatureMethod#RSA_SHA512}.
   * @since 11
   * @see SignatureMethod#RSA_SHA512
   */
  public static final String RSA_SHA512 = SignatureMethod.RSA_SHA512;

  /**
   * Example usage of the new field {@link SignatureMethod#SHA1_RSA_MGF1}.
   * @since 11
   * @see SignatureMethod#SHA1_RSA_MGF1
   */
  public static final String SHA1_RSA_MGF1 = SignatureMethod.SHA1_RSA_MGF1;

  /**
   * Example usage of the new field {@link SignatureMethod#SHA224_RSA_MGF1}.
   * @since 11
   * @see SignatureMethod#SHA224_RSA_MGF1
   */
  public static final String SHA224_RSA_MGF1 = SignatureMethod.SHA224_RSA_MGF1;

  /**
   * Example usage of the new field {@link SignatureMethod#SHA256_RSA_MGF1}.
   * @since 11
   * @see SignatureMethod#SHA256_RSA_MGF1
   */
  public static final String SHA256_RSA_MGF1 = SignatureMethod.SHA256_RSA_MGF1;

  /**
   * Example usage of the new field {@link SignatureMethod#SHA384_RSA_MGF1}.
   * @since 11
   * @see SignatureMethod#SHA384_RSA_MGF1
   */
  public static final String SHA384_RSA_MGF1 = SignatureMethod.SHA384_RSA_MGF1;

  /**
   * Example usage of the new field {@link SignatureMethod#SHA512_RSA_MGF1}.
   * @since 11
   * @see SignatureMethod#SHA512_RSA_MGF1
   */
  public static final String SHA512_RSA_MGF1 = SignatureMethod.SHA512_RSA_MGF1;

  /**
   * Example usage of the new field {@link SignatureMethod#ECDSA_SHA1}.
   * @since 11
   * @see SignatureMethod#ECDSA_SHA1
   */
  public static final String ECDSA_SHA1 = SignatureMethod.ECDSA_SHA1;

  /**
   * Example usage of the new field {@link SignatureMethod#ECDSA_SHA224}.
   * @since 11
   * @see SignatureMethod#ECDSA_SHA224
   */
  public static final String ECDSA_SHA224 = SignatureMethod.ECDSA_SHA224;

  /**
   * Example usage of the new field {@link SignatureMethod#ECDSA_SHA256}.
   * @since 11
   * @see SignatureMethod#ECDSA_SHA256
   */
  public static final String ECDSA_SHA256 = SignatureMethod.ECDSA_SHA256;

  /**
   * Example usage of the new field {@link SignatureMethod#ECDSA_SHA384}.
   * @since 11
   * @see SignatureMethod#ECDSA_SHA384
   */
  public static final String ECDSA_SHA384 = SignatureMethod.ECDSA_SHA384;

  /**
   * Example usage of the new field {@link SignatureMethod#ECDSA_SHA512}.
   * @since 11
   * @see SignatureMethod#ECDSA_SHA512
   */
  public static final String ECDSA_SHA512 = SignatureMethod.ECDSA_SHA512;

  /**
   * Example usage of the new field {@link SignatureMethod#HMAC_SHA224}.
   * @since 11
   * @see SignatureMethod#HMAC_SHA224
   */
  public static final String HMAC_SHA224 = SignatureMethod.HMAC_SHA224;

  /**
   * Example usage of the new field {@link SignatureMethod#HMAC_SHA256}.
   * @since 11
   * @see SignatureMethod#HMAC_SHA256
   */
  public static final String HMAC_SHA256 = SignatureMethod.HMAC_SHA256;

  /**
   * Example usage of the new field {@link SignatureMethod#HMAC_SHA384}.
   * @since 11
   * @see SignatureMethod#HMAC_SHA384
   */
  public static final String HMAC_SHA384 = SignatureMethod.HMAC_SHA384;

  /**
   * Example usage of the new field {@link SignatureMethod#HMAC_SHA512}.
   * @since 11
   * @see SignatureMethod#HMAC_SHA512
   */
  public static final String HMAC_SHA512 = SignatureMethod.HMAC_SHA512;

}
