package whatisnewin.javax.xml.crypto.dsig;

import javax.xml.crypto.dsig.DigestMethod;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link DigestMethod}
 * that were newly introduced in Java version 11.<br>
 *
 * {@link DigestMethod} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see DigestMethod
 */
public final class WhatIsNewInDigestMethod
{
  /**
   * Example usage of the new field {@link DigestMethod#SHA224}.
   * @since 11
   * @see DigestMethod#SHA224
   */
  public static final String SHA224 = DigestMethod.SHA224;

  /**
   * Example usage of the new field {@link DigestMethod#SHA384}.
   * @since 11
   * @see DigestMethod#SHA384
   */
  public static final String SHA384 = DigestMethod.SHA384;

  /**
   * Example usage of the new field {@link DigestMethod#SHA3_224}.
   * @since 11
   * @see DigestMethod#SHA3_224
   */
  public static final String SHA3_224 = DigestMethod.SHA3_224;

  /**
   * Example usage of the new field {@link DigestMethod#SHA3_256}.
   * @since 11
   * @see DigestMethod#SHA3_256
   */
  public static final String SHA3_256 = DigestMethod.SHA3_256;

  /**
   * Example usage of the new field {@link DigestMethod#SHA3_384}.
   * @since 11
   * @see DigestMethod#SHA3_384
   */
  public static final String SHA3_384 = DigestMethod.SHA3_384;

  /**
   * Example usage of the new field {@link DigestMethod#SHA3_512}.
   * @since 11
   * @see DigestMethod#SHA3_512
   */
  public static final String SHA3_512 = DigestMethod.SHA3_512;

}
